templateDir: ./sdk-resources/v2-resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.0.3
useSingleRequestParameter: true
